# Generated by Django 5.0 on 2024-01-02 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GymRoutine', '0003_record_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailexerciseroutine',
            name='lbs_kg',
            field=models.CharField(choices=[('lbs', 'lbs'), ('kg', 'kg')], default='kg', max_length=50),
        ),
    ]
